export type ICountry = {
    short: string;
    en: string;
    label: string;
    value: string;
};

export const countryOptions: ICountry[] = [
    {
        en: 'Philippines',
        short: 'PH',
        label: '63',
        value: '63',
    },
    {
        en: 'China',
        short: 'CN',
        label: '86',
        value: '86',
    },
    {
        en: 'Japan',
        short: 'JP',
        label: '81',
        value: '81',
    },
    {
        en: 'Hongkong',
        short: 'HK',
        label: '852',
        value: '852',
    },
    {
        en: 'Korea',
        short: 'KR',
        label: '82',
        value: '82',
    },
    // {
    //     en: 'Andorra',
    //     short: 'AD',
    //     label: '376',
    //     value: '376',
    // },
    // {
    //     en: 'Austria',
    //     short: 'AT',
    //     label: '43',
    //     value: '43',
    // },
    // {
    //     en: 'Australia',
    //     short: 'AU',
    //     label: '61',
    //     value: '61',
    // },
    // {
    //     en: 'Albania',
    //     short: 'AL',
    //     label: '355',
    //     value: '355',
    // },
    // {
    //     en: 'Algeria',
    //     short: 'DZ',
    //     label: '213',
    //     value: '213',
    // },
    // {
    //     en: 'Ireland',
    //     short: 'IE',
    //     label: '353',
    //     value: '353',
    // },
    // {
    //     en: 'Afghanistan',
    //     short: 'AF',
    //     label: '93',
    //     value: '93',
    // },
    // {
    //     en: 'Angola',
    //     short: 'AO',
    //     label: '244',
    //     value: '244',
    // },
    // {
    //     en: 'Anguilla',
    //     short: 'AI',
    //     label: '1264',
    //     value: '1264',
    // },
    // {
    //     en: 'Argentina',
    //     short: 'AR',
    //     label: '54',
    //     value: '54',
    // },
    // {
    //     en: 'UnitedArabEmirates',
    //     short: 'AE',
    //     label: '971',
    //     value: '971',
    // },
    // {
    //     en: 'Ascension',
    //     short: '',
    //     label: '247',
    //     value: '247',
    // },
    // {
    //     en: 'Oman',
    //     short: 'OM',
    //     label: '968',
    //     value: '968',
    // },
    // {
    //     en: 'Macao',
    //     short: 'MO',
    //     label: '853',
    //     value: '853',
    // },
    // {
    //     en: 'Armenia',
    //     short: 'AM',
    //     label: '374',
    //     value: '374',
    // },
    // {
    //     en: 'Azerbaijan',
    //     short: 'AZ',
    //     label: '994',
    //     value: '994',
    // },
    // {
    //     en: 'Ethiopia',
    //     short: 'ET',
    //     label: '251',
    //     value: '251',
    // },
    // {
    //     en: 'Estonia',
    //     short: 'EE',
    //     label: '372',
    //     value: '372',
    // },
    // {
    //     en: 'AntiguaandBarbuda',
    //     short: 'AG',
    //     label: '1268',
    //     value: '1268',
    // },
    // {
    //     en: 'Barbados',
    //     short: 'BB',
    //     label: '1246',
    //     value: '1246',
    // },
    // {
    //     en: 'PapuaNewCuinea',
    //     short: 'PG',
    //     label: '675',
    //     value: '675',
    // },
    // {
    //     en: 'Botswana',
    //     short: 'BW',
    //     label: '267',
    //     value: '267',
    // },
    // {
    //     en: 'Iceland',
    //     short: 'IS',
    //     label: '354',
    //     value: '354',
    // },
    // {
    //     en: 'PuertoRico',
    //     short: 'PR',
    //     label: '1787',
    //     value: '1787',
    // },
    // {
    //     en: 'Belarus',
    //     short: 'BY',
    //     label: '375',
    //     value: '375',
    // },
    // {
    //     en: 'Bahamas',
    //     short: 'BS',
    //     label: '1242',
    //     value: '1242',
    // },
    // {
    //     en: 'Bulgaria',
    //     short: 'BG',
    //     label: '359',
    //     value: '359',
    // },
    // {
    //     en: 'Burkina-faso',
    //     short: 'BF',
    //     label: '226',
    //     value: '226',
    // },
    // {
    //     en: 'Pakistan',
    //     short: 'PK',
    //     label: '92',
    //     value: '92',
    // },
    // {
    //     en: 'Poland',
    //     short: 'PL',
    //     label: '48',
    //     value: '48',
    // },
    // {
    //     en: 'Peru',
    //     short: 'PE',
    //     label: '51',
    //     value: '51',
    // },
    // {
    //     en: 'Benin',
    //     short: 'BJ',
    //     label: '229',
    //     value: '229',
    // },
    // {
    //     en: 'Bahrain',
    //     short: 'BH',
    //     label: '973',
    //     value: '973',
    // },
    // {
    //     en: 'Burundi',
    //     short: 'BI',
    //     label: '257',
    //     value: '257',
    // },
    // {
    //     en: 'Paraguay',
    //     short: 'PY',
    //     label: '595',
    //     value: '595',
    // },
    // {
    //     en: 'Belgium',
    //     short: 'BE',
    //     label: '32',
    //     value: '32',
    // },
    // {
    //     en: 'Palestine',
    //     short: 'BL',
    //     label: '970',
    //     value: '970',
    // },
    // {
    //     en: 'Bolivia',
    //     short: 'BO',
    //     label: '591',
    //     value: '591',
    // },
    // {
    //     en: 'Belize',
    //     short: 'BZ',
    //     label: '501',
    //     value: '501',
    // },
    // {
    //     en: 'BermudaIs.',
    //     short: 'BM',
    //     label: '1441',
    //     value: '1441',
    // },
    // {
    //     en: 'Panama',
    //     short: 'PA',
    //     label: '507',
    //     value: '507',
    // },
    // {
    //     en: 'Brazil',
    //     short: 'BR',
    //     label: '55',
    //     value: '55',
    // },
    // {
    //     en: 'NorthKorea',
    //     short: 'KP',
    //     label: '850',
    //     value: '850',
    // },
    // {
    //     en: 'Togo',
    //     short: 'TG',
    //     label: '228',
    //     value: '228',
    // },
    // {
    //     en: 'Germany',
    //     short: 'DE',
    //     label: '49',
    //     value: '49',
    // },
    // {
    //     en: 'Denmark',
    //     short: 'DK',
    //     label: '45',
    //     value: '45',
    // },
    // {
    //     en: 'DominicaRep.',
    //     short: 'DO',
    //     label: '1890',
    //     value: '1890',
    // },
    // {
    //     en: 'SamoaEastern',
    //     short: '',
    //     label: '684',
    //     value: '684',
    // },
    // {
    //     en: 'Ecuador',
    //     short: 'EC',
    //     label: '593',
    //     value: '593',
    // },
    // {
    //     en: 'Egypt',
    //     short: 'EG',
    //     label: '20',
    //     value: '20',
    // },
    // {
    //     en: 'Russia',
    //     short: 'RU',
    //     label: '7',
    //     value: '7',
    // },
    // {
    //     en: 'France',
    //     short: 'FR',
    //     label: '33',
    //     value: '33',
    // },
    // {
    //     en: 'Fiji',
    //     short: 'FJ',
    //     label: '679',
    //     value: '679',
    // },
    // {
    //     en: 'Finland',
    //     short: 'FI',
    //     label: '358',
    //     value: '358',
    // },
    // {
    //     en: 'FrenchPolynesia',
    //     short: 'PF',
    //     label: '689',
    //     value: '689',
    // },
    // {
    //     en: 'FrenchGuiana',
    //     short: 'GF',
    //     label: '594',
    //     value: '594',
    // },
    // {
    //     en: 'Cuba',
    //     short: 'CU',
    //     label: '53',
    //     value: '53',
    // },
    // {
    //     en: 'Gambia',
    //     short: 'GM',
    //     label: '220',
    //     value: '220',
    // },
    // {
    //     en: 'Guam',
    //     short: 'GU',
    //     label: '1671',
    //     value: '1671',
    // },
    // {
    //     en: 'Congo',
    //     short: 'CG',
    //     label: '242',
    //     value: '242',
    // },
    // {
    //     en: 'Colombia',
    //     short: 'CO',
    //     label: '57',
    //     value: '57',
    // },
    // {
    //     en: 'Georgia',
    //     short: 'GE',
    //     label: '995',
    //     value: '995',
    // },
    // {
    //     en: 'Grenada',
    //     short: 'GD',
    //     label: '1809',
    //     value: '1809',
    // },
    // {
    //     en: 'CostaRica',
    //     short: 'CR',
    //     label: '506',
    //     value: '506',
    // },
    // {
    //     en: 'Guyana',
    //     short: 'GY',
    //     label: '592',
    //     value: '592',
    // },
    // {
    //     en: 'Haiti',
    //     short: 'HT',
    //     label: '509',
    //     value: '509',
    // },
    // {
    //     en: 'Honduras',
    //     short: 'HN',
    //     label: '504',
    //     value: '504',
    // },
    // {
    //     en: 'Netherlands',
    //     short: 'NL',
    //     label: '31',
    //     value: '31',
    // },
    // {
    //     en: 'NetheriandsAntilles',
    //     short: '',
    //     label: '599',
    //     value: '599',
    // },
    // {
    //     en: 'Kazakstan',
    //     short: 'KZ',
    //     label: '327',
    //     value: '327',
    // },
    // {
    //     en: 'Zimbabwe',
    //     short: 'ZW',
    //     label: '263',
    //     value: '263',
    // },
    // {
    //     en: 'Djibouti',
    //     short: 'DJ',
    //     label: '253',
    //     value: '253',
    // },
    // {
    //     en: 'Kyrgyzstan',
    //     short: 'KG',
    //     label: '331',
    //     value: '331',
    // },
    // {
    //     en: 'Czech',
    //     short: 'CS',
    //     label: '420',
    //     value: '420',
    // },
    // {
    //     en: 'Ghana',
    //     short: 'GH',
    //     label: '233',
    //     value: '233',
    // },
    // {
    //     en: 'Canada',
    //     short: 'CA',
    //     label: '1',
    //     value: '1',
    // },
    // {
    //     en: 'Guinea',
    //     short: 'GN',
    //     label: '224',
    //     value: '224',
    // },
    // {
    //     en: 'Gabon',
    //     short: 'GA',
    //     label: '241',
    //     value: '241',
    // },
    // {
    //     en: 'Kampuchea(Cambodia)',
    //     short: 'KH',
    //     label: '855',
    //     value: '855',
    // },
    // {
    //     en: 'CookIs.',
    //     short: 'CK',
    //     label: '682',
    //     value: '682',
    // },
    // {
    //     en: 'Cameroon',
    //     short: 'CM',
    //     label: '237',
    //     value: '237',
    // },
    // {
    //     en: 'CaymanIs.',
    //     short: '',
    //     label: '1345',
    //     value: '1345',
    // },
    // {
    //     en: 'Kenya',
    //     short: 'KE',
    //     label: '254',
    //     value: '254',
    // },
    // {
    //     en: 'IvoryCoast',
    //     short: '',
    //     label: '225',
    //     value: '225',
    // },
    // {
    //     en: 'Qatar',
    //     short: 'QA',
    //     label: '974',
    //     value: '974',
    // },
    // {
    //     en: 'Kuwait',
    //     short: 'KW',
    //     label: '965',
    //     value: '965',
    // },
    // {
    //     en: 'Liberia',
    //     short: 'LR',
    //     label: '231',
    //     value: '231',
    // },
    // {
    //     en: 'Lebanon',
    //     short: 'LB',
    //     label: '961',
    //     value: '961',
    // },
    // {
    //     en: 'Libya',
    //     short: 'LY',
    //     label: '218',
    //     value: '218',
    // },
    // {
    //     en: 'Romania',
    //     short: 'RO',
    //     label: '40',
    //     value: '40',
    // },
    // {
    //     en: 'Reunion',
    //     short: '',
    //     label: '262',
    //     value: '262',
    // },
    // {
    //     en: 'Luxembourg',
    //     short: 'LU',
    //     label: '352',
    //     value: '352',
    // },
    // {
    //     en: 'Lesotho',
    //     short: 'LS',
    //     label: '266',
    //     value: '266',
    // },
    // {
    //     en: 'Lithuania',
    //     short: 'LT',
    //     label: '370',
    //     value: '370',
    // },
    // {
    //     en: 'Latvia',
    //     short: 'LV',
    //     label: '371',
    //     value: '371',
    // },
    // {
    //     en: 'Laos',
    //     short: 'LA',
    //     label: '856',
    //     value: '856',
    // },
    // {
    //     en: 'Liechtenstein',
    //     short: 'LI',
    //     label: '423',
    //     value: '423',
    // },
    // {
    //     en: 'Burma',
    //     short: 'MM',
    //     label: '95',
    //     value: '95',
    // },
    // {
    //     en: 'Madagascar',
    //     short: 'MG',
    //     label: '261',
    //     value: '261',
    // },
    // {
    //     en: 'Maldives',
    //     short: 'MV',
    //     label: '960',
    //     value: '960',
    // },
    // {
    //     en: 'Moldova,Republicof',
    //     short: 'MD',
    //     label: '373',
    //     value: '373',
    // },
    // {
    //     en: 'Malta',
    //     short: 'MT',
    //     label: '356',
    //     value: '356',
    // },
    // {
    //     en: 'UnitedStatesofAmerica',
    //     short: 'US',
    //     label: '1',
    //     value: '1',
    // },
    // {
    //     en: 'Mongolia',
    //     short: 'MN',
    //     label: '976',
    //     value: '976',
    // },
    // {
    //     en: 'Bangladesh',
    //     short: 'BD',
    //     label: '880',
    //     value: '880',
    // },
    // {
    //     en: 'Mali',
    //     short: 'ML',
    //     label: '223',
    //     value: '223',
    // },
    // {
    //     en: 'Morocco',
    //     short: 'MA',
    //     label: '212',
    //     value: '212',
    // },
    // {
    //     en: 'Mauritius',
    //     short: 'MU',
    //     label: '230',
    //     value: '230',
    // },
    // {
    //     en: 'Malawi',
    //     short: 'MW',
    //     label: '265',
    //     value: '265',
    // },
    // {
    //     en: 'Malaysia',
    //     short: 'MY',
    //     label: '60',
    //     value: '60',
    // },
    // {
    //     en: 'MarianaIs',
    //     short: '',
    //     label: '1670',
    //     value: '1670',
    // },
    // {
    //     en: 'Monaco',
    //     short: 'MC',
    //     label: '377',
    //     value: '377',
    // },
    // {
    //     en: 'Mozambique',
    //     short: 'MZ',
    //     label: '258',
    //     value: '258',
    // },
    // {
    //     en: 'Martinique',
    //     short: '',
    //     label: '596',
    //     value: '596',
    // },
    // {
    //     en: 'MontserratIs',
    //     short: 'MS',
    //     label: '1664',
    //     value: '1664',
    // },
    // {
    //     en: 'Mexico',
    //     short: 'MX',
    //     label: '52',
    //     value: '52',
    // },
    // {
    //     en: 'Nepal',
    //     short: 'NP',
    //     label: '977',
    //     value: '977',
    // },
    // {
    //     en: 'SouthAfrica',
    //     short: 'ZA',
    //     label: '27',
    //     value: '27',
    // },
    // {
    //     en: 'Nicaragua',
    //     short: 'NI',
    //     label: '505',
    //     value: '505',
    // },
    // {
    //     en: 'Nauru',
    //     short: 'NR',
    //     label: '674',
    //     value: '674',
    // },
    // {
    //     en: 'Namibia',
    //     short: 'NA',
    //     label: '264',
    //     value: '264',
    // },
    // {
    //     en: 'Nigeria',
    //     short: 'NG',
    //     label: '234',
    //     value: '234',
    // },
    // {
    //     en: 'Yugoslavia',
    //     short: 'YU',
    //     label: '381',
    //     value: '381',
    // },
    // {
    //     en: 'Norway',
    //     short: 'NO',
    //     label: '47',
    //     value: '47',
    // },
    // {
    //     en: 'Portugal',
    //     short: 'PT',
    //     label: '351',
    //     value: '351',
    // },
    // {
    //     en: 'Sweden',
    //     short: 'SE',
    //     label: '46',
    //     value: '46',
    // },
    // {
    //     en: 'Switzerland',
    //     short: 'CH',
    //     label: '41',
    //     value: '41',
    // },
    // {
    //     en: 'Sudan',
    //     short: 'SD',
    //     label: '249',
    //     value: '249',
    // },
    // {
    //     en: 'SaoTomeandPrincipe',
    //     short: 'ST',
    //     label: '239',
    //     value: '239',
    // },
    // {
    //     en: 'EISalvador',
    //     short: 'SV',
    //     label: '503',
    //     value: '503',
    // },
    // {
    //     en: 'Slovakia',
    //     short: 'SK',
    //     label: '421',
    //     value: '421',
    // },
    // {
    //     en: 'SierraLeone',
    //     short: 'SL',
    //     label: '232',
    //     value: '232',
    // },
    // {
    //     en: 'SriLanka',
    //     short: 'LK',
    //     label: '94',
    //     value: '94',
    // },
    // {
    //     en: 'SolomonIs',
    //     short: 'SB',
    //     label: '677',
    //     value: '677',
    // },
    // {
    //     en: 'Suriname',
    //     short: 'SR',
    //     label: '597',
    //     value: '597',
    // },
    // {
    //     en: 'Slovenia',
    //     short: 'SI',
    //     label: '386',
    //     value: '386',
    // },
    // {
    //     en: 'St.Lucia',
    //     short: 'LC',
    //     label: '1758',
    //     value: '1758',
    // },
    // {
    //     en: 'Somali',
    //     short: 'SO',
    //     label: '252',
    //     value: '252',
    // },
    // {
    //     en: 'SanMarino',
    //     short: 'SM',
    //     label: '378',
    //     value: '378',
    // },
    // {
    //     en: 'Senegal',
    //     short: 'SN',
    //     label: '221',
    //     value: '221',
    // },
    // {
    //     en: 'Cyprus',
    //     short: 'CY',
    //     label: '357',
    //     value: '357',
    // },
    // {
    //     en: 'Seychelles',
    //     short: 'SC',
    //     label: '248',
    //     value: '248',
    // },
    // {
    //     en: 'SaudiArabia',
    //     short: 'SA',
    //     label: '966',
    //     value: '966',
    // },
    // {
    //     en: 'Swaziland',
    //     short: 'SZ',
    //     label: '268',
    //     value: '268',
    // },
    // {
    //     en: 'SaintVincent',
    //     short: 'VC',
    //     label: '1784',
    //     value: '1784',
    // },
    // {
    //     en: 'Turkey',
    //     short: 'TR',
    //     label: '90',
    //     value: '90',
    // },
    // {
    //     en: 'Thailand',
    //     short: 'TH',
    //     label: '66',
    //     value: '66',
    // },
    // {
    //     en: 'Tonga',
    //     short: 'TO',
    //     label: '676',
    //     value: '676',
    // },
    // {
    //     en: 'Tajikstan',
    //     short: 'TJ',
    //     label: '992',
    //     value: '992',
    // },
    // {
    //     en: 'Turkmenistan',
    //     short: 'TM',
    //     label: '993',
    //     value: '993',
    // },
    // {
    //     en: 'TrinidadandTobago',
    //     short: 'TT',
    //     label: '1809',
    //     value: '1809',
    // },
    // {
    //     en: 'Tunisia',
    //     short: 'TN',
    //     label: '216',
    //     value: '216',
    // },
    // {
    //     en: 'Tanzania',
    //     short: 'TZ',
    //     label: '255',
    //     value: '255',
    // },
    // {
    //     en: 'Taiwan',
    //     short: 'TW',
    //     label: '886',
    //     value: '886',
    // },
    // {
    //     en: 'Guatemala',
    //     short: 'GT',
    //     label: '502',
    //     value: '502',
    // },
    // {
    //     en: 'Uganda',
    //     short: 'UG',
    //     label: '256',
    //     value: '256',
    // },
    // {
    //     en: 'Ukraine',
    //     short: 'UA',
    //     label: '380',
    //     value: '380',
    // },
    // {
    //     en: 'Brunei',
    //     short: 'BN',
    //     label: '673',
    //     value: '673',
    // },
    // {
    //     en: 'Uruguay',
    //     short: 'UY',
    //     label: '598',
    //     value: '598',
    // },
    // {
    //     en: 'Venezuela',
    //     short: 'VE',
    //     label: '58',
    //     value: '58',
    // },
    // {
    //     en: 'Uzbekistan',
    //     short: 'UZ',
    //     label: '233',
    //     value: '233',
    // },
    // {
    //     en: 'Spain',
    //     short: 'ES',
    //     label: '34',
    //     value: '34',
    // },

    // {
    //     en: 'Singapore',
    //     short: 'SG',
    //     label: '65',
    //     value: '65',
    // },
    // {
    //     en: 'Greece',
    //     short: 'GR',
    //     label: '30',
    //     value: '30',
    // },
    // {
    //     en: 'Syria',
    //     short: 'SY',
    //     label: '963',
    //     value: '963',
    // },
    // {
    //     en: 'SamoaWest',
    //     short: '',
    //     label: '685',
    //     value: '685',
    // },
    // {
    //     en: 'NewZealand',
    //     short: 'NZ',
    //     label: '64',
    //     value: '64',
    // },
    // {
    //     en: 'Hungary',
    //     short: 'HU',
    //     label: '36',
    //     value: '36',
    // },
    // {
    //     en: 'Jordan',
    //     short: 'JO',
    //     label: '962',
    //     value: '962',
    // },
    // {
    //     en: 'India',
    //     short: 'IN',
    //     label: '91',
    //     value: '91',
    // },
    // {
    //     en: 'Italy',
    //     short: 'IT',
    //     label: '39',
    //     value: '39',
    // },
    // {
    //     en: 'Indonesia',
    //     short: 'ID',
    //     label: '62',
    //     value: '62',
    // },
    // {
    //     en: 'UnitedKiongdom',
    //     short: 'GB',
    //     label: '44',
    //     value: '44',
    // },
    // {
    //     en: 'Iran',
    //     short: 'IR',
    //     label: '98',
    //     value: '98',
    // },
    // {
    //     en: 'Iraq',
    //     short: 'IQ',
    //     label: '964',
    //     value: '964',
    // },
    // {
    //     en: 'Yemen',
    //     short: 'YE',
    //     label: '967',
    //     value: '967',
    // },
    // {
    //     en: 'Jamaica',
    //     short: 'JM',
    //     label: '1876',
    //     value: '1876',
    // },
    // {
    //     en: 'Vietnam',
    //     short: 'VN',
    //     label: '84',
    //     value: '84',
    // },
    // {
    //     en: 'Israel',
    //     short: 'IL',
    //     label: '972',
    //     value: '972',
    // },
    // {
    //     en: 'Gibraltar',
    //     short: 'GI',
    //     label: '350',
    //     value: '350',
    // },
    // {
    //     en: 'Zambia',
    //     short: 'ZM',
    //     label: '260',
    //     value: '260',
    // },
    // {
    //     en: 'Chad',
    //     short: 'TD',
    //     label: '235',
    //     value: '235',
    // },
    // {
    //     en: 'CentralAfricanRepublic',
    //     short: 'CF',
    //     label: '236',
    //     value: '236',
    // },
    // {
    //     en: 'Chile',
    //     short: 'CL',
    //     label: '56',
    //     value: '56',
    // },
    // {
    //     en: 'Zaire',
    //     short: 'ZR',
    //     label: '243',
    //     value: '243',
    // },
];
