const {
    REACT_APP_API_URL,
    REACT_APP_CRYPTO_STORAGE_KEY,
    REACT_APP_VIEWPORTWIDTH,
    REACT_APP_VERSION,
    REACT_APP_ACCOUNT_AES_KEY,
    REACT_APP_IMAGE_URL,
} = process.env;

const API_URL = REACT_APP_API_URL;
const IMAGE_URL = REACT_APP_IMAGE_URL;
const CRYPTO_STORAGE_KEY = REACT_APP_CRYPTO_STORAGE_KEY;
const VIEWPORTWIDTH = REACT_APP_VIEWPORTWIDTH;
const VERSION = REACT_APP_VERSION;
const ACCOUNT_AES_KEY = REACT_APP_ACCOUNT_AES_KEY;

export {
    API_URL,
    CRYPTO_STORAGE_KEY,
    VIEWPORTWIDTH,
    VERSION,
    ACCOUNT_AES_KEY,
    IMAGE_URL,
};
